{% set name = "compliance-checker" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/compliance_checker-{{ version }}.tar.gz
  sha256: 92b01dd2de0b51fc32c25972a42d392ca6e633c197252ed285443482800a2baa

build:
  entry_points:
    - compliance-checker = cchecker:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cf-units >=2
    - cftime >=1.1.0
    - importlib-metadata
    - importlib-resources
    - isodate >=0.6.1
    - jinja2 >=2.7.3
    - lxml >=3.2.1
    - netcdf4 >=1.6.4
    - owslib >=0.8.3
    - packaging
    - pendulum >=1.2.4
    - pygeoif >=0.6
    - pyproj >=2.2.1
    - regex >=2017.07.28
    - requests >=2.2.1
    - setuptools >=15.0
    - shapely >=1.7.1
    - validators >=0.14.2

test:
  source_files:
    - compliance_checker
  requires:
    - pytest
    - pip
    - python {{ python_min }}
  imports:
    - compliance_checker
    - compliance_checker.cf
  commands:
    - pip check
    - compliance-checker --help

about:
  home: https://github.com/ioos/compliance-checker
  license: Apache-2.0
  license_file: LICENSE
  summary: Checks Datasets and SOS endpoints for standards compliance

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
