{% set version = "3.0.2" %}

package:
  name: compliance-checker
  version: {{ version }}

source:
  fn: compliance-checker-{{ version }}.tar.gz
  url: https://github.com/ioos/compliance-checker/archive/{{ version }}.tar.gz
  sha256: 6f2aa01f1f0d6978cabdb51e0e0c12dc03c9e8954189a7bb6eb7c1630d868bce

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - compliance-checker = cchecker:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - arrow
    - cf_units
    - isodate
    - jinja2
    - lxml
    - owslib
    - pygeoif
    - requests

test:
  source_files:
    - compliance_checker
  requires:
    - pytest
    - httpretty  # [not py3k]
  imports:
    - compliance_checker
    - compliance_checker.cf
    - compliance_checker.tests
  commands:
    - py.test -s -rxs -v compliance_checker  # [not (py3k or win)]
    - compliance-checker --help

about:
  home: https://github.com/ioos/compliance-checker
  license: Apache 2.0
  summary: 'Checks Datasets and SOS endpoints for standards compliance.'

extra:
  recipe-maintainers:
    - benjwadams
    - daf
    - kwilcox
    - lukecampbell
    - ocefpaf
