travis:
  secure:
    BINSTAR_TOKEN: sFK6ncrBkQy2GZNbXjhyrqabJ6G4YQl7vNNClNEzgWm/39pqzkuvmq/7RnJNyeCShe/kXjjPK2CSSyrAW5s/zm4W6RuuCkXtONoZZgM9EbBS+xmoIQrQFHkXtCOWk2rp8zwihFgNuYeYnoKXCRFad3LxWp6ZwT74g+a0z/sm51gBBbaDdkqBxK5qZEvNFCFqCfkjKkq/gp9xd4abMMXpVecfJhnbWUj6MAUddlWbQVlonuj/DNqy1EPCyJ2LknA2YtkmVRjNndk3YTQKtFA/t0cVBoO7MD/T+X1AK520zpylxmej2WP9ipsCn+4d2k++pCxTLzYYABMTmMxnD4Vls1Q+4Z7h6Lu1UKoiwUmLn+A7ggplcK/+yrQpdyJYyYGvQKNOD778BkQyoCT2qNnG2n2YIjw1yFMiYtZN0SOOO/t34OeEdMItm5S2qJgxFVHkA6AfJm0rUfZBzAcfpvZNl1ue68xFV/+cvA9umd/rwHzg85VHONX5dSDoLkPnfskgFWvuzgm++Mp3aR8oXG12RCdJAPos46D+yJtb+kYGpPTUmKZfMay+2uT3qgsfus3PhkNCDwZoVByzOcc7N9qbvYR/eURAs+tAnkFVNIMnl2M8CqWHuUGpnUC6hORqrdOimL05r4Jw3OUTPktcE5BNEb66FBBQXA+WBgGUiAfST/I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
bot:
  automerge: true
